'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProductDetails

    '''<summary>
    '''tblDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblDetail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPrdCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrdCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrdCodeValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrdCodeValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrdDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrdDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrdDescvalue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrdDescvalue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrdBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrdBrand As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrdBrandValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrdBrandValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrdManuType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrdManuType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrdManuTypeValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrdManuTypeValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrdType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrdType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrdTypeValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrdTypeValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrdOrigin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrdOrigin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrdOriginValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrdOriginValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPurchaseType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPurchaseType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPurchaseTypeValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPurchaseTypeValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDistributionType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDistributionType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDistributionTypeValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDistributionTypeValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrivateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrivateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrivateLabelValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrivateLabelValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOnOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnOrder As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOnOrderValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnOrderValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBalQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBalQty As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBalQtyValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBalQtyValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBalValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBalValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBalValValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBalValValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIndent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIndent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIndentValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIndentValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFresh As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFreshValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFreshValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCreateDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreateDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCreateDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreateDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDeranged control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeranged As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDerangedValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDerangedValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblShelfLife control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShelfLife As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblShelfLifeValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShelfLifeValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrintDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrintDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrintDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrintDateValue As Global.System.Web.UI.WebControls.Label
End Class
