'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Master_File_ProductHierarchySimp

    '''<summary>
    '''tblDetail1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblDetail1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPrdCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrdCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrdCodeValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrdCodeValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrdDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrdDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrdDescvalue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrdDescvalue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPurchaseType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPurchaseType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPurchaseTypeValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPurchaseTypeValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDistributionTypeValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDistributionTypeValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLRC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLRC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPriceType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPriceTypeValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceTypeValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBalQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBalQty As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBalQtyValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBalQtyValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRegularPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegularPrice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRegularPriceValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegularPriceValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentPrice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentPriceValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentPriceValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRegStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegStartDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRegStartDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegStartDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentPriceStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentPriceStartDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentPriceStartDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentPriceStartDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRegEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegEndDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRegEndDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegEndDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentEndDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentEndDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentEndDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPWPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPWPrice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPWPriceValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPWPriceValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIsRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIsRange As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblISRangeVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblISRangeVal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPWPriceStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPWPriceStartDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPWPriceStartDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPWPriceStartDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDeranged control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeranged As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDerangedValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDerangedValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPWPriceEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPWPriceEndDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPWPriceEndDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPWPriceEndDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOnOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnOrder As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOnOrderValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnOrderValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIBTOnOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIBTOnOrder As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIBTOnOrderValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIBTOnOrderValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trDimension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDimension As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDim1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDim1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDim1Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDim1Value As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDim2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDim2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDim2Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDim2Value As Global.System.Web.UI.WebControls.Label
End Class
