'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ServerFileDialog

    '''<summary>
    '''divFileList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFileList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tdButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdButton As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''upButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upButton As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ibtnOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnOk As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCancel As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''upTree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upTree As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''xdsServer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xdsServer As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''tvServerFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tvServerFile As Global.System.Web.UI.WebControls.TreeView

    '''<summary>
    '''tServerFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tServerFile As Global.System.Web.UI.Timer

    '''<summary>
    '''btnServerFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnServerFile As Global.System.Web.UI.WebControls.Button
End Class
